name: voice_todo
description: A Flutter-based Voice-Driven To-Do List App prototype.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  speech_to_text: ^7.0.0
  flutter_tts: ^3.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.9.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
